#!/usr/bin/env python3
from os import environ
from subprocess import run, PIPE

display = environ["DISPLAY"]
print(f"Display is {display}")

result = run(["xauth", "extract", "-", display], stdout=PIPE, check=True)

cookie_bytes = bytearray(result.stdout)
cookie_bytes[0] = 0xff
cookie_bytes[1] = 0xff

xauth = environ["XAUTHORITY"]
print(f"Auth is {xauth}")
run(["xauth", "merge", xauth, "-"], input=cookie_bytes, check=True)